version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    env_file: .env
    ports:
      - "5433:5432"
    mem_limit: 512m
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  prefect:
    image: prefecthq/prefect:3-latest
    container_name: etl_prefect
    mem_limit: 2gb
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0 --port 4200

  scraper:
    build: ./scraper
    depends_on:
      - postgres
    env_file: .env
    mem_limit: 1gb
    environment:
      # nadpisanie tylko tego, co musi być inne wewnątrz kontenera
      - DB_HOST=postgres
      - DB_PORT=5432

  aggregator:
    build: ./aggregator
    depends_on:
      - postgres
    env_file: .env
    mem_limit: 512m
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

  analyzer:
    build: ./analyzer
    depends_on:
      - postgres
    env_file: .env
    mem_limit: 512m
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

volumes:
  pgdata: