services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    env_file: .env
    ports:
      - "5433:5432"
    mem_limit: 512m
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  prefect:
    image: prefecthq/prefect:3-latest
    container_name: etl_prefect
    mem_limit: 2gb
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0 --port 4200

  scraper:
    build: ./scraper
    depends_on:
      - postgres
    env_file: .env
    mem_limit: 1gb
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

  aggregator:
    build: ./aggregator
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://etl_user:etl_pass@postgres:5432/etl_db
    depends_on:
      - postgres
      - analyzer
    mem_limit: 512m

  analyzer:
    build: ./analyzer
    environment:
      - DATABASE_URL=postgresql://etl_user:etl_pass@postgres:5432/etl_db
    depends_on:
      - postgres
    mem_limit: 512m

volumes:
  pgdata: